spring:
  application:
    name: api-gateway

  boot:
    admin:
      client:
        instance:
          service-host-type: ip
        url: http://${DATASOURCE_HOST:localhost}:8081


server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
